import { useState, useEffect } from "react";
import { ArrowLeft } from "lucide-react";

export default function SamRep({ onBack }) {
  const [isMobile, setIsMobile] = useState(
    typeof window !== "undefined" && window.innerWidth < 768
  );

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 768);
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const sampleReport = {
    solicitation: "DHA Video Imaging Archive",
    solicitationId: "DHANOISS022426",
    agency: "Defense Health Agency",
    analysisTime: "83 seconds",
    riskScore: "HIGH",

    executiveSummary:
      "BidSmith analysis identified critical RMF compliance dependencies and Authority to Operate (ATO) requirements that could materially affect proposal eligibility. Several integration constraints with legacy systems introduce moderate operational risk.",

    complianceRisks: [
      {
        category: "RMF Compliance",
        riskLevel: "HIGH",
        notes: "Legacy platform must demonstrate RMF alignment before deployment.",
      },
      {
        category: "Authority to Operate (ATO)",
        riskLevel: "HIGH",
        notes: "System must operate inside accredited federal environment.",
      },
      {
        category: "Data Handling",
        riskLevel: "MEDIUM",
        notes: "Federal healthcare data standards referenced in attachments.",
      },
      {
        category: "Legacy System Integration",
        riskLevel: "MEDIUM",
        notes: "Compatibility requirements partially defined.",
      },
    ],

    bidKillers: [
      "SPRS score submission required prior to proposal evaluation.",
      "Demonstrated experience with RMF-accredited environments expected.",
      "Failure to provide ATO pathway documentation may disqualify bid.",
    ],

    evaluationCriteria: [
      "Technical compliance weighted more heavily than cost.",
      "Cybersecurity architecture will be evaluated early in scoring.",
      "Past performance with federal health systems preferred.",
    ],

    recommendation: "CONDITIONAL BID",

    conditions: [
      "Provide RMF compliance mapping.",
      "Document ATO accreditation strategy.",
      "Validate compatibility with legacy imaging infrastructure.",
    ],
  };

  const riskColor = (level) => {
    if (level === "HIGH") return "#dc2626";
    if (level === "MEDIUM") return "#f59e0b";
    return "#10b981";
  };

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#f8fafc",
        padding: isMobile ? "20px" : "60px 40px",
        fontFamily: "Inter, sans-serif",
      }}
    >
      {/* Navigation */}
      <nav
        style={{
          display: "flex",
          alignItems: "center",
          marginBottom: 40,
        }}
      >
        <button
          onClick={() => (onBack ? onBack() : (window.location.href = "/"))}
          style={{
            display: "flex",
            alignItems: "center",
            gap: 6,
            border: "1px solid #e2e8f0",
            background: "#fff",
            borderRadius: 8,
            padding: "8px 12px",
            cursor: "pointer",
          }}
        >
          <ArrowLeft size={16} />
          {isMobile ? "Back" : "Back to Home"}
        </button>
      </nav>

      <div style={{ maxWidth: 900, margin: "0 auto" }}>
        {/* Credibility Note */}
        <p
          style={{
            fontSize: 14,
            color: "#64748b",
            marginBottom: 24,
          }}
        >
          Sample audit generated by BidSmith from a Defense Health Agency
          solicitation. Full reports analyze 300+ page RFPs in under 90 seconds.
        </p>

        {/* Header */}
        <div
          style={{
            background: "#fff",
            border: "1px solid #e2e8f0",
            borderRadius: 12,
            padding: 32,
            marginBottom: 30,
          }}
        >
          <h1 style={{ fontSize: 32, marginBottom: 16 }}>
            BidSmith Compliance Risk Audit
          </h1>

          <div style={{ lineHeight: 1.8 }}>
            <div>
              <strong>Solicitation:</strong> {sampleReport.solicitation}
            </div>

            <div>
              <strong>Solicitation ID:</strong> {sampleReport.solicitationId}
            </div>

            <div>
              <strong>Agency:</strong> {sampleReport.agency}
            </div>

            <div>
              <strong>Analysis Time:</strong> {sampleReport.analysisTime}
            </div>

            <div>
              <strong>Risk Score:</strong>{" "}
              <span
                style={{
                  color: riskColor(sampleReport.riskScore),
                  fontWeight: "bold",
                }}
              >
                {sampleReport.riskScore}
              </span>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <Section title="1. Executive Summary">
          <p>{sampleReport.executiveSummary}</p>
        </Section>

        {/* Compliance Risks */}
        <Section title="2. Compliance Risk Findings">
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr>
                <th style={th}>Category</th>
                <th style={th}>Risk</th>
                <th style={th}>Notes</th>
              </tr>
            </thead>

            <tbody>
              {sampleReport.complianceRisks.map((r, i) => (
                <tr key={i}>
                  <td style={td}>{r.category}</td>

                  <td style={td}>
                    <span
                      style={{
                        color: riskColor(r.riskLevel),
                        fontWeight: "bold",
                      }}
                    >
                      {r.riskLevel}
                    </span>
                  </td>

                  <td style={td}>{r.notes}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Section>

        {/* Bid Killer Detection */}
        <Section title="3. Bid-Killer Detection">
          <ul>
            {sampleReport.bidKillers.map((k, i) => (
              <li key={i}>{k}</li>
            ))}
          </ul>
        </Section>

        {/* Evaluation Criteria */}
        <Section title="4. Evaluation Criteria Signals">
          <ul>
            {sampleReport.evaluationCriteria.map((c, i) => (
              <li key={i}>{c}</li>
            ))}
          </ul>
        </Section>

        {/* Recommendation */}
        <Section title="5. Bid / No-Bid Recommendation">
          <div
            style={{
              background: "#fef3c7",
              padding: 20,
              borderRadius: 10,
            }}
          >
            <strong>{sampleReport.recommendation}</strong>

            <ul style={{ marginTop: 10 }}>
              {sampleReport.conditions.map((c, i) => (
                <li key={i}>{c}</li>
              ))}
            </ul>
          </div>
        </Section>

        {/* Footer */}
        <div style={{ marginTop: 50, textAlign: "center", color: "#64748b" }}>
          Generated by <strong>BidSmith</strong> — AI Compliance Intelligence
          for Federal RFPs
        </div>

        {/* CTA */}
        <div style={{ marginTop: 40, textAlign: "center" }}>
          <button
            onClick={() =>
              window.open("https://bidsmith.pro", "_blank", "noopener")
            }
            style={{
              background: "#2563eb",
              color: "#fff",
              border: "none",
              borderRadius: 8,
              padding: "12px 20px",
              fontWeight: 600,
              cursor: "pointer",
            }}
          >
            Analyze Your Solicitation
          </button>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div
      style={{
        background: "#fff",
        border: "1px solid #e2e8f0",
        borderRadius: 12,
        padding: 30,
        marginBottom: 30,
      }}
    >
      <h2 style={{ marginBottom: 16 }}>{title}</h2>
      {children}
    </div>
  );
}

const th = {
  textAlign: "left",
  padding: "10px",
  borderBottom: "1px solid #e2e8f0",
};

const td = {
  padding: "10px",
  borderBottom: "1px solid #f1f5f9",
};