import React, { useState } from 'react';
import { FileText, FileCode, Loader } from 'lucide-react';

const mdContent = () => `# BidSmith Intelligence Report
**Solicitation:** DHA Video Imaging Archive
**Agency:** Defense Health Agency
**Solicitation ID:** DHANOISS022426
**Generated:** ${new Date().toUTCString()}
**Analysis Latency:** 42 seconds · Time Saved: ~18 hrs

---

## 1. Risk Assessment
- **Overall Risk Score:** 93 / 100
- **Bid Recommendation:** CONDITIONAL BID
- **Confidence:** 98% · Clauses Flagged: 14

---

## 2. BidSmith Intelligence Index™
| Metric | Score |
|---|---|
| Opportunity Score | 92 / 100 |
| Bid Probability | 85% |
| Est. Win Rate | 68% (w/o ATO) |
| Technical Alignment | 93 |
| Competitive Position | 88 |
| Compliance Readiness | 72 |
| Past Performance Fit | 86 |

---

## 3. Executive Summary
BidSmith analysis identified critical RMF compliance dependencies and Authority to Operate (ATO) requirements that could materially affect proposal eligibility. Several integration constraints with legacy systems introduce moderate operational risk.

---

## 4. Bid Recommendation: CONDITIONAL BID
- Demonstrate RMF alignment
- Provide ATO pathway documentation at IL4 or above
- Confirm legacy system compatibility
- Post NIST SP 800-171 score to SPRS

---

## 5. Risk Flags & Bid-Killer Alerts

### ⛔ RF-001 — Authority to Operate (ATO) [HIGH / BID-KILLER]
Section M.3 mandates ATO at IL4+. Missing SPRS entry = automatic disqualification.
**Action:** Document ATO pathway or obtain waiver before submission.

### ⛔ RF-002 — NIST SP 800-171 Score Not in SPRS [HIGH / BID-KILLER]
Cybersecurity score must be active in SPRS at time of submission.
**Action:** Complete self-assessment and post score to SPRS immediately.

### ⚠️ RF-003 — Past Performance Threshold [MEDIUM]
Requires 3 references >$5M in last 5 years. Only 2 identified.
**Action:** Identify and prepare a third qualifying reference.

### ⚠️ RF-004 — PIEE Portal Submission Window [MEDIUM]
**Action:** Register on PIEE and confirm submission window.

### ⚠️ RF-005 — PII/PHI Data Handling Unspecified [MEDIUM]
**Action:** Add data handling section to Technical Approach volume.

---

## 6. Compliance Matrix (FAR Referenced)

| ID | Requirement | FAR Reference | Status | Risk |
|---|---|---|---|---|
| CM-01 | SAM.gov Registration | FAR 52.204-7 | ✅ Compliant | LOW |
| CM-02 | NIST SP 800-171 / SPRS | DFARS 252.204-7012 | ❌ Non-Compliant | HIGH |
| CM-03 | Authority to Operate | N/A | ⚠️ Conditional | HIGH |
| CM-04 | Small Business Set-Aside | FAR 52.219-6 | ✅ Compliant | LOW |
| CM-05 | Past Performance (3 refs $5M+) | FAR Part 15 | ⚠️ Conditional | MEDIUM |
| CM-06 | PII/PHI Data Handling | N/A | ⚠️ Conditional | HIGH |
| CM-07 | NAICS Code Compliance | FAR Part 19 | ✅ Compliant | LOW |
| CM-08 | PIEE Portal Submission | FAR 52.212-1 | 🔍 Review | MEDIUM |
| CM-09 | Bid Bond Requirements | FAR Part 28 | ✅ Compliant | LOW |
| CM-10 | Security Clearance | N/A | ⚠️ Conditional | MEDIUM |
| CM-11 | Subcontracting Plan | FAR 52.219-9 | 🔍 Review | MEDIUM |
| CM-12 | FAR Clause Compliance | Various | ✅ Compliant | LOW |

---

*Generated by BidSmith Intelligence Engine · ARIS Protocol · bidsmith.pro*
*Zero Fluff. High Conviction. Time Saved: ~14 hours.*
`;

export const triggerPDFExport = async () => {
  const element = document.getElementById('dashboard-content');
  if (!element) return;

  // Force background before capture so html2canvas doesn't get transparent
  const prevBg = element.style.background;
  element.style.background = '#0b1220';

  try {
    const html2pdf = (await import('html2pdf.js')).default;
    await html2pdf()
      .set({
        margin:      [8, 8, 8, 8],
        filename:    'BidSmith-Intelligence-Report.pdf',
        image:       { type: 'jpeg', quality: 1 },
        html2canvas: {
          scale: 2,
          useCORS: true,
          backgroundColor: '#0b1220',
          windowWidth: 1400,
          logging: false,
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
      })
      .from(element)
      .save();
  } catch (err) {
    console.error('PDF export failed:', err);
    window.print();
  } finally {
    element.style.background = prevBg;
  }
};

const ExportToolbar = () => {
  const [pdfLoading, setPdfLoading] = useState(false);
  const [mdLoading,  setMdLoading]  = useState(false);

  const handlePDF = async () => {
    setPdfLoading(true);
    await triggerPDFExport();
    setPdfLoading(false);
  };

  const handleMarkdown = () => {
    setMdLoading(true);
    try {
      const blob = new Blob([mdContent()], { type: 'text/markdown' });
      const url  = URL.createObjectURL(blob);
      const a    = document.createElement('a');
      a.href     = url;
      a.download = 'BidSmith-Intelligence-Report.md';
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('MD export failed:', err);
    } finally {
      setMdLoading(false);
    }
  };

  const btnStyle = (loading) => ({
    display: 'flex', alignItems: 'center', gap: '7px',
    padding: '7px 14px',
    backgroundColor: 'var(--card)',
    color: loading ? 'var(--text-secondary)' : 'var(--text-primary)',
    border: '1px solid var(--border)',
    borderRadius: '5px',
    cursor: loading ? 'wait' : 'pointer',
    fontSize: '11px', fontWeight: 700, letterSpacing: '0.06em',
    transition: 'all 0.15s',
    opacity: loading ? 0.6 : 1,
  });

  return (
    <div style={{ 
      display: 'flex', 
      alignItems: 'center', 
      gap: '8px', 
      flexWrap: 'wrap', 
      justifyContent: 'flex-start' 
    }}>
      <button style={btnStyle(pdfLoading)} onClick={handlePDF} disabled={pdfLoading}>
        {pdfLoading
          ? <Loader size={13} style={{ animation: 'spin 1s linear infinite' }} />
          : <FileText size={13} />}
        {pdfLoading ? 'Generating...' : 'Export PDF'}
      </button>

      <button style={btnStyle(mdLoading)} onClick={handleMarkdown} disabled={mdLoading}>
        {mdLoading
          ? <Loader size={13} style={{ animation: 'spin 1s linear infinite' }} />
          : <FileCode size={13} />}
        {mdLoading ? 'Exporting...' : 'Export .MD'}
      </button>
    </div>
  );
};

export default ExportToolbar;
