/**
 * BidOutputCard — Drafted bid summary with one-click clipboard copy.
 * Formats the audit result into a clean, copy-able brief.
 * Props:
 *   auditResult — full audit JSON
 *   loading     — bool, shows skeleton while inference runs
 */
import { useState } from 'react';
import { ClipboardCopy, Check, FileOutput, Database, Cpu, Clock } from 'lucide-react';

// ── Format audit as markdown for clipboard ────────────────────────────────────
function formatForClipboard(audit) {
  if (!audit) return '';

  const v = audit.verdict || {};
  const intel = audit.intelligence || {};
  const reqs = Array.isArray(audit.requirements) ? audit.requirements : [];

  const lines = [
    `# BidSmith Audit Brief`,
    `**Solicitation:** ${audit.solicitation_number || 'N/A'}`,
    `**Agency:** ${audit.agency || 'N/A'}`,
    `**Contract Type:** ${audit.contract_type || 'N/A'}`,
    `**Set-Aside:** ${audit.set_aside_type || 'N/A'}`,
    `**Due Date:** ${audit.due_date || 'N/A'}`,
    ``,
    `## Verdict: ${v.recommendation || 'CONDITIONAL'}`,
    `Win Probability: ${v.win_probability ?? '–'}%  |  Confidence: ${v.confidence || 'MEDIUM'}`,
    ``,
    v.rationale ? `**Rationale:** ${v.rationale}` : '',
    ``,
    audit.executiveSummary ? `## Executive Summary\n${audit.executiveSummary}` : '',
    ``,
    reqs.length > 0
      ? `## Compliance Matrix (${reqs.length} requirements)\n` +
        reqs.slice(0, 10).map(r =>
          `- [${r.status === 'compliant' || r.met ? '✓' : '✗'}] ${r.requirement || r.text || 'Requirement'}`
        ).join('\n') + (reqs.length > 10 ? `\n…and ${reqs.length - 10} more` : '')
      : '',
    ``,
    Array.isArray(intel.top_risks) && intel.top_risks.length > 0
      ? `## Top Risk Signals\n` + intel.top_risks.slice(0, 5).map(r => `- ${r}`).join('\n')
      : '',
    ``,
    `---`,
    `Generated by BidSmith · ${new Date().toLocaleString()}`,
  ];

  return lines.filter(l => l !== null && l !== undefined).join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

// ── Skeleton ──────────────────────────────────────────────────────────────────
function Bone({ w = '100%', h = 11, radius = 5, style = {} }) {
  return (
    <div style={{
      width: w, height: h, borderRadius: radius,
      background: 'linear-gradient(90deg,#1a1a1a 25%,#242424 50%,#1a1a1a 75%)',
      backgroundSize: '200% 100%',
      animation: 'shimmer 1.6s infinite',
      ...style,
    }} />
  );
}

function SkeletonBody() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      <div style={{ display: 'flex', gap: 8 }}>
        <Bone w={80} h={28} radius={8} />
        <Bone w={60} h={28} radius={8} />
      </div>
      <Bone w="100%" />
      <Bone w="85%" />
      <Bone w="92%" />
      <Bone w="70%" />
    </div>
  );
}

// ── Main ──────────────────────────────────────────────────────────────────────
export default function BidOutputCard({ auditResult, loading = false }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const text = formatForClipboard(auditResult);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    } catch {
      // Fallback for non-secure contexts
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    }
  };

  const v = auditResult?.verdict || {};
  const isInsufficient = v.recommendation === 'INSUFFICIENT_DATA' || auditResult?.queued;
  const hasData = !!auditResult && !loading && !isInsufficient;

  const verdictColor = v.recommendation === 'BID'
    ? '#22c55e' : v.recommendation === 'NO-BID'
    ? '#ef4444' : '#f59e0b';

  return (
    <div style={s.card}>
      {/* Header */}
      <div style={s.header}>
        <div style={s.headerLeft}>
          <div style={s.iconWrap}>
            <FileOutput size={14} color="#f59e0b" />
          </div>
          <span style={s.title}>Bid Brief</span>
        </div>

        {/* Copy button — the primary CTA */}
        <button
          style={{
            ...s.copyBtn,
            ...(copied ? s.copyBtnSuccess : {}),
            ...(!hasData ? s.copyBtnDisabled : {}),
          }}
          onClick={handleCopy}
          disabled={!hasData}
          title="Copy audit brief to clipboard"
        >
          {copied ? (
            <><Check size={12} style={{ marginRight: 5 }} />Copied!</>
          ) : (
            <><ClipboardCopy size={12} style={{ marginRight: 5 }} />Copy Brief</>
          )}
        </button>
      </div>

      {loading ? (
        <SkeletonBody />
      ) : isInsufficient ? (
        <div style={s.empty}>
          <p style={{ ...s.emptyText, color: '#f59e0b' }}>
            {auditResult?.queued
              ? 'Queued for manual review — check back shortly.'
              : 'Upload a government solicitation PDF or SAM.gov link to generate a brief.'}
          </p>
          {!auditResult?.queued && (
            <p style={{ ...s.emptyText, marginTop: 4, fontSize: 10 }}>
              If this keeps happening, verify OPENROUTER_API_KEY / GEMINI_API_KEY in your .env
            </p>
          )}
        </div>
      ) : !hasData ? (
        <div style={s.empty}>
          <p style={s.emptyText}>Run an audit to generate a copyable brief</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {/* Verdict pill */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{
              fontSize: 18, fontWeight: 800,
              color: verdictColor, letterSpacing: '-0.03em',
            }}>
              {v.recommendation || 'CONDITIONAL'}
            </span>
            {typeof v.win_probability === 'number' && (
              <span style={s.probBadge}>
                {v.win_probability}% win prob.
              </span>
            )}
          </div>

          {/* Summary */}
          {auditResult.executiveSummary && (
            <p style={s.summaryText}>
              {auditResult.executiveSummary.slice(0, 280)}
              {auditResult.executiveSummary.length > 280 ? '…' : ''}
            </p>
          )}

          {/* Key metadata row */}
          <div style={s.metaRow}>
            {auditResult.agency && (
              <span style={s.metaChip}>{auditResult.agency}</span>
            )}
            {auditResult.contract_type && (
              <span style={s.metaChip}>{auditResult.contract_type}</span>
            )}
            {auditResult.set_aside_type && (
              <span style={s.metaChip}>{auditResult.set_aside_type}</span>
            )}
          </div>

          {/* Rationale */}
          {v.rationale && (
            <p style={s.rationaleText}>
              {v.rationale.slice(0, 200)}{v.rationale.length > 200 ? '…' : ''}
            </p>
          )}

          {/* ── Audit Metadata ── */}
          <AuditMeta audit={auditResult} />
        </div>
      )}
    </div>
  );
}

// ── Audit provenance strip ─────────────────────────────────────────────────────
function AuditMeta({ audit }) {
  if (!audit) return null;
  const meta         = audit.meta || {};
  const oppId        = audit.opportunity_id || audit.solicitation_number || null;
  const genAt        = audit.generated_at ? new Date(audit.generated_at) : null;
  const genFormatted = genAt ? genAt.toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit', timeZoneName: 'short' }) : null;
  const version      = meta.logic_gate_version || 'v2.2';
  const cacheHit     = Boolean(meta.cache_hit);
  const servedAt     = meta.cache_served_at ? new Date(meta.cache_served_at) : null;

  return (
    <div style={m.wrap}>
      <p style={m.label}>AUDIT PROVENANCE</p>
      <div style={m.grid}>
        {oppId && (
          <div style={m.row}>
            <Database size={9} color="#4b5563" style={{ flexShrink: 0 }} />
            <span style={m.key}>Opportunity</span>
            <span style={m.val}>{oppId}</span>
          </div>
        )}
        {genFormatted && (
          <div style={m.row}>
            <Clock size={9} color="#4b5563" style={{ flexShrink: 0 }} />
            <span style={m.key}>Generated</span>
            <span style={m.val}>{genFormatted}</span>
          </div>
        )}
        <div style={m.row}>
          <Cpu size={9} color="#4b5563" style={{ flexShrink: 0 }} />
          <span style={m.key}>Logic Gate</span>
          <span style={{ ...m.val, fontFamily: 'monospace', color: '#6366f1' }}>{version}</span>
        </div>
        <div style={m.row}>
          <span style={{ width: 9, flexShrink: 0 }} />
          <span style={m.key}>Source</span>
          <span style={{
            ...m.val,
            color: cacheHit ? '#22c55e' : '#6b7280',
            fontWeight: 700,
          }}>
            {cacheHit ? `CACHE HIT${servedAt ? ` · ${servedAt.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}` : ''}` : 'LIVE INFERENCE'}
          </span>
        </div>
      </div>
    </div>
  );
}

const m = {
  wrap: {
    borderTop: '1px solid #1a1a1a',
    paddingTop: 12,
    marginTop: 4,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  label: {
    margin: 0, fontSize: '9px', fontWeight: 700,
    letterSpacing: '0.1em', color: '#2a2a2a', textTransform: 'uppercase',
  },
  grid: { display: 'flex', flexDirection: 'column', gap: 5 },
  row: { display: 'flex', alignItems: 'center', gap: 6 },
  key: {
    fontSize: 10, color: '#4b5563', width: 72, flexShrink: 0,
    letterSpacing: '-0.01em',
  },
  val: {
    fontSize: 10, color: '#6b7280', letterSpacing: '-0.01em',
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
  },
};

// ── Styles ────────────────────────────────────────────────────────────────────
const s = {
  card: {
    background: '#111111',
    border: '1px solid #1f1f1f',
    borderRadius: 16,
    padding: '20px 20px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    height: '100%',
    boxSizing: 'border-box',
  },
  header: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 8 },
  iconWrap: {
    width: 26, height: 26, borderRadius: 7,
    background: 'rgba(245,158,11,0.1)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  title: {
    fontSize: 13, fontWeight: 600, color: '#f9fafb', letterSpacing: '-0.01em',
  },
  copyBtn: {
    display: 'inline-flex', alignItems: 'center',
    fontSize: 12, fontWeight: 600,
    color: '#f9fafb',
    background: '#1a1a1a',
    border: '1px solid #2a2a2a',
    borderRadius: 8,
    padding: '6px 12px',
    cursor: 'pointer',
    transition: 'all 0.15s',
    letterSpacing: '-0.01em',
    whiteSpace: 'nowrap',
  },
  copyBtnSuccess: {
    background: 'rgba(34,197,94,0.1)',
    borderColor: 'rgba(34,197,94,0.25)',
    color: '#22c55e',
  },
  copyBtnDisabled: {
    opacity: 0.3,
    cursor: 'not-allowed',
  },
  empty: {
    flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center',
    padding: '20px 0',
  },
  emptyText: {
    margin: 0, fontSize: 12, color: '#374151', textAlign: 'center',
  },
  probBadge: {
    fontSize: 11, fontWeight: 500, color: '#6b7280',
    background: '#0d0d0d', border: '1px solid #1f1f1f',
    borderRadius: 20, padding: '2px 8px',
  },
  summaryText: {
    margin: 0, fontSize: 12, color: '#9ca3af', lineHeight: 1.65,
  },
  metaRow: { display: 'flex', flexWrap: 'wrap', gap: 5 },
  metaChip: {
    fontSize: 10, fontWeight: 500, color: '#6b7280',
    background: '#0d0d0d', border: '1px solid #1a1a1a',
    borderRadius: 5, padding: '3px 7px',
  },
  rationaleText: {
    margin: 0, fontSize: 11, color: '#4b5563', lineHeight: 1.6,
    borderTop: '1px solid #1a1a1a', paddingTop: 10,
  },
};
