import { Redis } from "@upstash/redis";
import { Index } from "@upstash/vector";

/**
 * ARIS Stateless Infrastructure Wrapper
 * Handles Ephemeral RAG and Usage Tracking without local state.
 */

// ─── Redis (Usage Tracking) ───────────────────────────────────────────────
export const redis = (process.env.UPSTASH_REDIS_REST_URL && process.env.UPSTASH_REDIS_REST_TOKEN)
  ? new Redis({
      url: process.env.UPSTASH_REDIS_REST_URL,
      token: process.env.UPSTASH_REDIS_REST_TOKEN,
    })
  : null;

/**
 * Atomic monthly usage increment.
 * Accepts a userId (preferred) or falls back to IP for anonymous users.
 */
export async function incrMonthlyUsage(clientId) {
  if (!redis) return { count: 1, reset: "static" }; // Fallback to limited trace

  const now = new Date();
  const monthKey = `aris:usage:${clientId}:${now.getFullYear()}-${now.getMonth()}`;

  const count = await redis.incr(monthKey);
  if (count === 1) {
    // Set expiry to 32 days on first hit of the month
    await redis.expire(monthKey, 32 * 24 * 60 * 60);
  }

  return { count };
}

// ─── Vector (Stateless RAG) ───────────────────────────────────────────────
export const vectorIndex = (process.env.UPSTASH_VECTOR_REST_URL && process.env.UPSTASH_VECTOR_REST_TOKEN)
  ? new Index({
      url: process.env.UPSTASH_VECTOR_REST_URL,
      token: process.env.UPSTASH_VECTOR_REST_TOKEN,
    })
  : null;

/**
 * Shred and index a massive solicitation for ephemeral RAG.
 * Uses sessionId as a metadata filter to maintain multi-tenant statelessness.
 */
export async function indexSolicitation(sessionId, chunks) {
  if (!vectorIndex) return false;
  
  // Format: [{ id, vector, metadata: { sessionId, text } }]
  // Note: Vectors should be generated by the caller or an embedding utility
  const records = chunks.map((chunk, i) => ({
    id: `chunk:${sessionId}:${i}`,
    metadata: { sessionId, text: chunk.content, section: chunk.section }
  }));

  // Upsert to Upstash Vector (assuming client handles embeddings automatically or via proxy)
  await vectorIndex.upsert(records);
  return true;
}

/**
 * Global Indexing for Sovereign Search V3 (Cross-Session)
 * Used to build the "Google of Federal Data" repository.
 */
export async function indexGlobalOpportunities(opportunities) {
  if (!vectorIndex) return false;
  
  const records = opportunities.map(opt => ({
    id: `opt:${opt.noticeId || opt.id}`,
    metadata: { 
      type: "global_opportunity",
      title: opt.title,
      agency: opt.agency || opt.organization,
      postedDate: opt.postedDate || opt.publishDate,
      region: opt.region || "US",
      url: opt.url || (opt.region === "IN" ? opt.link : `https://sam.gov/opp/${opt.noticeId || opt.id}/view`)
    }
  }));

  await vectorIndex.upsert(records);
  return true;
}

/**
 * Validate sessionId to prevent filter injection.
 * Only allows alphanumeric characters, hyphens, and underscores.
 */
function validateSessionId(sessionId) {
  if (!sessionId || !/^[a-zA-Z0-9_-]+$/.test(sessionId)) {
    throw new Error("Invalid sessionId format");
  }
  return sessionId;
}

/**
 * Query specifically for this session's documents.
 */
export async function querySolicitation(sessionId, queryVector, topK = 5) {
  if (!vectorIndex) return [];

  validateSessionId(sessionId);

  const results = await vectorIndex.query({
    vector: queryVector,
    topK,
    filter: `sessionId = '${sessionId}'`,
    includeMetadata: true
  });

  return results.map(r => r.metadata?.text).filter(Boolean);
}

/**
 * Wipe session vectors immediately after analysis completion to ensure statelessness.
 */
export async function wipeSessionVectors(sessionId) {
  if (!vectorIndex) return;

  validateSessionId(sessionId);

  try {
    // Fetch all vector IDs belonging to this session, then delete them
    const results = await vectorIndex.query({
      data: sessionId,
      topK: 1000,
      filter: `sessionId = '${sessionId}'`,
      includeMetadata: false
    });

    if (results.length > 0) {
      await vectorIndex.delete(results.map(r => r.id));
    }
  } catch (err) {
    console.error("[VECTOR] Failed to wipe session vectors:", err.message);
  }
}
