import { Redis } from "@upstash/redis";
import { Index } from "@upstash/vector";

/**
 * ARIS Stateless Infrastructure Wrapper
 * Handles Ephemeral RAG and Usage Tracking without local state.
 */

// ─── Redis (Usage Tracking) ───────────────────────────────────────────────
export const redis = (process.env.UPSTASH_REDIS_REST_URL && process.env.UPSTASH_REDIS_REST_TOKEN)
  ? new Redis({
      url: process.env.UPSTASH_REDIS_REST_URL,
      token: process.env.UPSTASH_REDIS_REST_TOKEN,
    })
  : null;

/**
 * Atomic monthly usage increment
 */
export async function incrMonthlyUsage(clientIP) {
  if (!redis) return { count: 1, reset: "static" }; // Fallback to limited trace
  
  const now = new Date();
  const monthKey = `aris:usage:${clientIP}:${now.getFullYear()}-${now.getMonth()}`;
  
  const count = await redis.incr(monthKey);
  if (count === 1) {
    // Set expiry to 32 days on first hit of the month
    await redis.expire(monthKey, 32 * 24 * 60 * 60);
  }
  
  return { count };
}

// ─── Vector (Stateless RAG) ───────────────────────────────────────────────
export const vectorIndex = (process.env.UPSTASH_VECTOR_REST_URL && process.env.UPSTASH_VECTOR_REST_TOKEN)
  ? new Index({
      url: process.env.UPSTASH_VECTOR_REST_URL,
      token: process.env.UPSTASH_VECTOR_REST_TOKEN,
    })
  : null;

/**
 * Shred and index a massive solicitation for ephemeral RAG.
 * Uses sessionId as a metadata filter to maintain multi-tenant statelessness.
 */
export async function indexSolicitation(sessionId, chunks) {
  if (!vectorIndex) return false;
  
  // Format: [{ id, vector, metadata: { sessionId, text } }]
  // Note: Vectors should be generated by the caller or an embedding utility
  const records = chunks.map((chunk, i) => ({
    id: `chunk:${sessionId}:${i}`,
    metadata: { sessionId, text: chunk.content, section: chunk.section }
  }));

  // Upsert to Upstash Vector (assuming client handles embeddings automatically or via proxy)
  await vectorIndex.upsert(records);
  return true;
}

/**
 * Query specifically for this session's documents.
 */
export async function querySolicitation(sessionId, queryVector, topK = 5) {
  if (!vectorIndex) return [];
  
  const results = await vectorIndex.query({
    vector: queryVector,
    topK,
    filter: `sessionId = '${sessionId}'`,
    includeMetadata: true
  });
  
  return results.map(r => r.metadata?.text).filter(Boolean);
}

/**
 * Wipe session vectors immediately after analysis completion to ensure statelessness.
 */
export async function wipeSessionVectors(sessionId) {
  if (!vectorIndex) return;
  
  // In a real implementation with high volume, consider using Namespaces for easier wiping.
  // For now, delete by IDs generated during indexing.
  // ... delete logic
}
